#!/usr/bin/env bash

function usage () {
	local name=`basename $0`
	echo "usage: $name <go-source-file> ..."
	exit 1
}

if test -z "$*"; then
	usage
fi

FILES=()
ARGS=()
DONE_WITH_FILES=

for arg in "$@"; do
	if test "$arg" = "--"; then
		DONE_WITH_FILES=1
		continue
	fi
	
	if test -n "$DONE_WITH_FILES"; then
		ARGS[${#ARGS[*]}]="$arg"
	else
		if ! test -f "$arg"; then
			echo "file not found: $arg"
			usage
		fi
		FILES[${#FILES[*]}]="$arg"
	fi
done

TMPDIR=`mktemp -d -t "godo.$RANDOM.$$"`

if test $? != 0; then
	echo "could not create temporary directory... sigh"
	exit 1
fi

SRCDIR="$TMPDIR/src"
mkdir "$SRCDIR"

for file in "${FILES[@]}"; do
	DESTFILE="$SRCDIR/$file"
	if test "#!" = `head -n1 "$file" | cut -c 1-2 `; then
		sed -n '2,$p' $file > $DESTFILE
	else
		cp "$file" $DESTFILE
	fi
done

cat > $TMPDIR/Makefile <<EOF
include \$(GOROOT)/src/Make.inc
TARG=tmp.out
GOFILES=$SRCDIR/*
include \$(GOROOT)/src/Make.cmd
EOF

make --silent --directory=$TMPDIR && $TMPDIR/tmp.out "${ARGS[@]}"
rm -rf $TMPDIR